config/routes.rb
Altria::Application.routes.draw do
  root to: "jobs#index"

  resources :jobs, shallow: true do
    resources :builds, only: [:index, :show, :create, :update, :destroy]
  end

  resources :events, only: :index if Rails.configuration.cache_classes
end

app/models/build.rb
class Build < ActiveRecord::Base
  include Altria::Proprietary

  serialize :properties, Hash

  validates :job_id, presence: true

  belongs_to :job, touch: true, counter_cache: true

  scope :recent, -> { order("created_at DESC") }

  scope :finished, -> { where("finished_at IS NOT NULL") }

  scope :unfinished, -> { where("finished_at IS NULL") }

  scope :started, -> { where("started_at IS NOT NULL") }

  scope :running, -> { started.unfinished }

  after_create { update_incremental_id }

  validate :one_job_cannot_have_more_than_two_builds, on: :create

  paginates_per 10

  def self.latest
    recent.first
  end

  # Pushes this build to worker's queue.
  def enqueue
    BuildWorker.perform_async(id)
  end

  # Runs this build, usually called from BuildWorker#perform.
  def run
    start
    finish(job.run)
  end

  # Returns elapsed sec as a Float or nil.
  def sec
    finished_at - started_at if finished_at && started_at
  end

  def status_name
    case status
    when true
      "success"
    when false
      "failure"
    when nil
      "unfinished"
    end
  end

  private

  def notify(type)
    $redis.publish("build.#{type}", notified_data)
  end

  def notified_data
    { id: id, job_id: job.id, status: status_name, finished_at: finished_at }.to_json
  end

  def start
    update_attributes!(started_at: Time.now)
    notify(:started)
  end

  def finish(result)
    reload.update_attributes!(finished_at: Time.now, output: result[:output], status: result[:status])
    notify(:finished)
  end

  def update_incremental_id
    update_attributes(incremental_id: job.builds_count + 1)
  end

  private

  def one_job_cannot_have_more_than_two_builds
    if job.builds.unfinished.any?
      errors.add(:id, "One job cannot have more than two builds")
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Altria::Proprietary

  serialize :properties, Hash

  validates :name, presence: true

  has_many :builds

  scope :recent, -> { order("updated_at DESC") }

  delegate :status, :status_name, :status_icon_css_class, to: :last_finished_build, allow_nil: true

  delegate :scheduled?, to: :scheduler, allow_nil: true

  property(:description, type: :text)

  property(:script, type: :text)

  property(:schedule, placeholder: "* * * * *")

  class << self
    def create_with_properties(params)
      new.update_attributes_with_properties(params)
    end

    def scheduled
      select(&:scheduled?)
    end

    def before_enqueue(&block)
      before_enqueues << block
    end

    def before_enqueues
      @before_enqueues ||= []
    end

    def after_enqueue(&block)
      after_enqueues << block
    end

    def after_enqueues
      @after_enqueues ||= []
    end

    def before_execute(&block)
      before_executes << block
    end

    def before_executes
      @before_executes ||= []
    end

    def after_execute(&block)
      after_executes << block
    end

    def after_executes
      @after_executes ||= []
    end
  end

  def run
    script ? execute : raise_script_not_found
  end

  def scheduler
    Altria::Scheduler.new(schedule) if schedule.present?
  end

  def enqueue
    builds.create.tap(&:enqueue).tap { execute_after_enqueues }
  end

  def enqueue_with_before_enqueues
    enqueue if execute_before_enqueues
  end

  def status_name
    builds.last.try(:status_name) || "unfinished"
  end

  def current_build
    builds.running.latest
  end

  def last_finished_build
    builds.finished.order(:finished_at).last
  end

  def update_attributes_with_properties(params)
    params.slice(:name, *self.class.property_names).each {|key, value| send("#{key}=", value) }
    tap(&:save)
  end

  def workspace
    @workspace ||= Altria::Workspace.new(workspace_path)
  end

  def workspace_path
    Altria.configuration.workspace_path + "jobs/#{id}"
  end

  def execute
    execute_before_executes
    execute_without_before_executes.tap { execute_after_executes }
  end

  private

  def execute_without_before_executes
    workspace.chdir { execute_script }
  end

  def execute_script
    result = Altria::Executer.execute(script)
    return unless result
    current_build.update_attributes!(output: result[:output], status: result[:status])
    result
  end

  def execute_before_enqueues
    self.class.before_enqueues.all? {|hook| instance_exec(&hook) != false }
  end

  def execute_after_enqueues
    self.class.after_enqueues.all? {|hook| instance_exec(&hook) != false }
  end

  def execute_before_executes
    self.class.before_executes.all? {|hook| instance_exec(&hook) != false }
  end

  def execute_after_executes
    self.class.after_executes.all? {|hook| instance_exec(&hook) != false }
  end

  def raise_script_not_found
    raise ScriptNotFound, 'You must set properties["script"]'
  end

  class ScriptNotFound < StandardError; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :html, :json

  self.responder = Altria::Responder

  rescue_from WeakParameters::ValidationError do
    head 400
  end

  # Cache to use `view_context.content_for` from controller.
  # This hack is nice to hook view_context from a plugin.
  #
  # Examples
  #
  #   JobsController.before_action do
  #     view_context.content_for :jobs_show, "This is a footer."
  #   end
  #
  def view_context
    @view_context ||= super
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :require_job, only: [:index, :create]
  before_action :require_resources, only: :index
  before_action :require_resource, only: [:show, :update, :destroy]

  validates :update do
    integer :status
  end

  def index
    respond_with @resources
  end

  def show
    respond_with @resource, layout: !request.xhr?
  end

  def create
    respond_with @job.enqueue
  end

  def update
    respond_with @resource.update_attributes(params.permit(:status))
  end

  def destroy
    respond_with @resource.destroy
  end

  private

  def require_job
    @job = Job.find(params[:job_id])
  end

  def scope
    @job.builds
  end

  def require_resources
    @resources = @job.builds
  end

  def require_resource
    @resource = Build.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ActionController::Live

  before_action :require_event_stream

  def index
    redis = Redis.new
    redis.psubscribe("build.*") do |on|
      on.pmessage do |pattern, event, data|
        response.stream.write("event: #{event}\n")
        response.stream.write("data: #{data}\n\n")
      end
    end
  rescue IOError
  rescue Redis::CannotConnectError
    head 503
  ensure
    redis.quit rescue nil
    response.stream.close
  end

  private

  def require_event_stream
    response.headers["Content-Type"] = "text/event-stream"
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_resources, only: :index
  before_action :require_resource, only: [:show, :edit, :update, :destroy]

  validates :create do
    string :name, required: true
  end

  validates :update do
    string :name
  end

  def index
    respond_with @resources
  end

  def show
    respond_with @resource, layout: !request.xhr?
  end

  def new
    respond_with @resource = scope.new
  end

  def create
    respond_with @resource = scope.create_with_properties(params)
  end

  def update
    respond_with @resource.update_attributes_with_properties(params)
  end

  def destroy
    respond_with @resource.destroy
  end

  private

  def scope
    Job.all
  end

  def require_resources
    @resources = scope
  end

  def require_resource
    @resource = scope.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def action_classes
    %W[#{controller_name}_controller #{action_name}_action]
  end
end

app/views/builds/_list.html.slim
li class=build.status_name id="build#{build.id}"
  = link_to build do
    span.id ##{build.incremental_id}
    span.time= build.finished_at

app/views/builds/show.html.slim
- if request.xhr? && params[:type] == "list"
  = render "builds/list", build: @resource

- else
  section.breadcrumbs
    ul
      li= link_to "Home", root_path
      li.delimiter
      li= link_to @resource.job.name, @resource.job
      li.delimiter
      li= link_to "##{@resource.id}", @resource

  section.build class = @resource.status_name
    h1
      span ##{@resource.incremental_id}

    table
      tr
        td started_at
        td= ":"
        td= @resource.started_at

      tr
        td finished_at
        td= ":"
        td= @resource.finished_at

      tr
        td sec
        td= ":"
        td= @resource.sec

      tr
        td status
        td= ":"
        td= @resource.status_name

    pre
      code
        = @resource.output

  = content_for :builds_show

app/views/jobs/_form.html.slim
section.job_settings
  h1 Settings

  = form_for resource, as: "" do |f|
    .field
      p= f.label :name
      p= f.text_field :name, placeholder: "required"

    - resource.class.properties.each do |property|
      .field
        p= f.label property.name
        p
          - case property.type
          - when :boolean
            = f.check_box property.name, {}, "true", "false"
          - when :text
            = f.text_area property.name, rows: 3
          - else
            = f.text_field property.name, placeholder: property.options[:placeholder]

    .field
      p= f.submit class: "button"

app/views/jobs/_list.html.slim
li class=job.status_name id="job#{job.id}"
  = link_to job do
    span
      = job.name

app/views/jobs/edit.html.slim
section.breadcrumbs
  ul
    li= link_to "Home", root_path
    li.delimiter
    li= link_to @resource.name, @resource
    li.delimiter
    li= link_to "settings", edit_job_path(@resource)

= render "form", resource: @resource

app/views/jobs/index.html.slim
section.breadcrumbs
  ul
    li= link_to "Home", root_path

section.jobs
  h1 JOBS

  p #{Job.count} jobs are found.


  .buttons
    = link_to "New", [:new, :job], class: "button new"

  ul
    - @resources.recent.each do |resource|
      = render "jobs/list", job: resource

app/views/jobs/new.html.slim
section.breadcrumbs
  ul
    li= link_to "Home", root_path
    li.delimiter
    li= link_to "Create Job", @resource

= render "form", resource: @resource

app/views/jobs/show.html.slim
- if request.xhr?
  = render "jobs/list", job: @resource

- else
  section.breadcrumbs
    ul
      li= link_to "Home", root_path
      li.delimiter
      li= link_to @resource.name, @resource

  section.builds
    h1
      = @resource.name

    p
      = @resource.description || "(no description)"

    .buttons
      = link_to "Run", [@resource, :builds], method: "POST", class: "button run"
      = link_to "Settings", [:edit, @resource], class: "button settings"
      = link_to "Delete", @resource, method: "DELETE", data: { confirm: "Are you sure?" }, class: "button delete"

    ul
      - @resource.builds.page(params[:page]).recent.limit(10).each do |build|
        = render "builds/list", build: build

    = paginate @resource.builds.page(params[:page])

  = content_for :jobs_show

app/views/layouts/application.html.slim
doctype html
html
  head
    title altria
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = content_for :head

  body class = action_classes
    = yield